### ISSUE TITLE
Make reusable

### ISSUE THREAD

**Issue by bonndan** [dmccabe/khexgrid#1]
I tried to include khexgrid in a project using jitpack without success (see https://jitpack.io/com/github/dmccabe/khexgrid/-0fe89fde22-1/build.log and https://jitpack.io/#dmccabe/khexgrid)

To fix this, you might:

- create a release on GitHub (idk if that is sufficient)
- fix the compilation error in build.gradle.kts
- publish khexgrid to maven central
- include a how to in the readme

Thanks

**Comment by dmccabe** [comment]
Thanks for the feedback. I do have CI setup on the repo and the [latest build](https://github.com/dmccabe/khexgrid/actions/runs/5122673504/jobs/9212080848) looks fine. A quick test locally using `.\gradlew build` worked fine as well. I think the `build.gradle.kts` file is valid in its current state based on that.

I haven't used Jitpack before, but a quick glance at the [docs](https://jitpack.io/docs/BUILDING/) leads me to believe the issue there is because we don't include the `maven` or `maven-publish` plugins. I can give that a quick try to see if that fixes the issue. Creating a release should be pretty low effort, I can do that too.

I mostly published this repo to help someone on the LibGDX Discord, so I don't have plans to do too much with it. I don't mind spending a few minutes to see if I can make it easier to reuse though.

**Comment by dmccabe** [comment]
I added `maven-publish` to the `build.gradle.kts` file and created a `v0.1.0` release, hopefully that does the trick.

**Comment by dmccabe** [comment]
That did the trick. I added the `maven-publish` plugin and added a `publishing` section to the Gradle file that pushes to Jitpack to resolve the issue. There's now a functional [0.1.0 build on Jitpack](https://jitpack.io/com/github/dmccabe/khexgrid/0.1.0/build.log).

**Comment by bonndan** [comment]
Worked. Awesome! 🎉
